# Fly.io deployment configuration for News Aggregator
# Deploy with: flyctl deploy

app = "match-news-aggregator"
primary_region = "iad"  # US East

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  LOG_LEVEL = "INFO"
  PYTHONPATH = "/app"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "1s"
    method = "get"
    path = "/api/v1/health"
    protocol = "http"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
  [http_service.concurrency]
    type = "requests"
    hard_limit = 200
    soft_limit = 100

# Machine configuration for free tier
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

# Secrets to set with: flyctl secrets set KEY=value
# MONGODB_CONNECTION_STRING
# REDDIT_CLIENT_ID
# REDDIT_CLIENT_SECRET
# GUARDIAN_API_KEY
# NEWSDATA_API_KEY
# CURRENTS_API_KEY