/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for AI agent match analysis snapshots
 */
export interface MatchAnalysis {
  /**
   * Unique identifier for the match
   */
  matchId: string;
  /**
   * Timestamp of when the snapshot was taken
   */
  snapshotTs: string;
  /**
   * Current status of the match
   */
  status: "PRE" | "LIVE" | "HT" | "FT";
  /**
   * Array of AI insights for the match
   */
  aiInsights: {
    /**
     * Unique identifier for the insight
     */
    id: string;
    /**
     * Markdown content of the insight
     */
    content: string;
    /**
     * Confidence score of the insight (0-1)
     */
    confidence: number;
    [k: string]: unknown;
  }[];
  /**
   * Optional statistics related to the match
   */
  stats?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
